# Site settings
course_name: Introduction to Computer Vision
course_description: "Introduction to Computer Vision provides a comprehensive introduction to fundamental techniques that enable computers to extract, process, and interpret information from digital images. The course covers core image processing methods including point processing for brightness and contrast adjustment, linear shift invariant systems and convolution for filtering operations, various image filtering techniques (smoothing, sharpening, noise reduction), and Fourier Transform for frequency domain analysis, and much more ..."
course_semester: "Spring 2026"

baseurl: "/it-intro-to-cv" # the subpath of your site, e.g. /blog/
url: "http://liaoux.github.io/" # the base hostname & protocol for your site

schoolname: "International University of Rabat"
schoolurl: "https://uir.ac.ma"
# twitter_username: username 

address: |
    School of Computer Science and Digital Engineering (ESIN)
    UIR - Morocco

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%A %d %b %Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
